import type { User, Category, Item, Claim } from './types';
import { PlaceHolderImages } from './placeholder-images';

export const users: User[] = [
  { id: 'user-1', name: 'Alex Doe', email: 'alex@example.com', avatarUrl: 'https://i.pravatar.cc/150?u=user1' },
  { id: 'user-2', name: 'Sam Smith', email: 'sam@example.com', avatarUrl: 'https://i.pravatar.cc/150?u=user2' },
];

export const categories: Category[] = [
  { id: 'electronics', name: 'Electronics' },
  { id: 'books', name: 'Books' },
  { id: 'clothing', name: 'Clothing' },
  { id: 'accessories', name: 'Accessories' },
  { id: 'other', name: 'Other' },
];

export const items: Item[] = [
  {
    id: '1',
    name: 'Bose Headphones',
    description: 'Black Bose QuietComfort headphones in a black case. Last seen near the library entrance.',
    category: categories[0],
    status: 'lost',
    location: 'Library',
    date: '2024-07-20',
    imageUrl: PlaceHolderImages.find(p => p.id === 'item-1')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'item-1')?.imageHint || '',
    userId: 'user-1',
  },
  {
    id: '2',
    name: 'Intro to Physics Textbook',
    description: 'Found this textbook on a bench in the main quad. Has some highlighting in the first few chapters.',
    category: categories[1],
    status: 'found',
    location: 'Main Quad',
    date: '2024-07-19',
    imageUrl: PlaceHolderImages.find(p => p.id === 'item-2')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'item-2')?.imageHint || '',
    userId: 'user-2',
  },
  {
    id: '3',
    name: 'Apartment Keys',
    description: 'Lost my keys, it has a blue lanyard attached. Probably dropped them somewhere in the student center.',
    category: categories[4],
    status: 'lost',
    location: 'Student Center',
    date: '2024-07-21',
    imageUrl: PlaceHolderImages.find(p => p.id === 'item-3')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'item-3')?.imageHint || '',
    userId: 'user-2',
  },
  {
    id: '4',
    name: 'Blue Water Bottle',
    description: 'Found a blue Hydro Flask near the gym. It has a few stickers on it.',
    category: categories[3],
    status: 'found',
    location: 'Gym',
    date: '2024-07-22',
    imageUrl: PlaceHolderImages.find(p => p.id === 'item-4')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'item-4')?.imageHint || '',
    userId: 'user-1',
  },
  {
    id: '5',
    name: 'Leather Wallet',
    description: 'A black leather wallet found in lecture hall 3B.',
    category: categories[3],
    status: 'found',
    location: 'Lecture Hall 3B',
    date: '2024-07-18',
    imageUrl: PlaceHolderImages.find(p => p.id === 'item-5')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'item-5')?.imageHint || '',
    userId: 'user-2',
  },
  {
    id: '6',
    name: 'University Hoodie',
    description: 'Left my gray university hoodie in the cafeteria.',
    category: categories[2],
    status: 'lost',
    location: 'Cafeteria',
    date: '2024-07-20',
    imageUrl: PlaceHolderImages.find(p => p.id === 'item-6')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'item-6')?.imageHint || '',
    userId: 'user-1',
  },
   {
    id: '7',
    name: 'Macbook Pro',
    description: 'Silver Macbook Pro with a sticker on the cover. Found in the computer lab.',
    category: categories[0],
    status: 'found',
    location: 'Computer Lab',
    date: '2024-07-22',
    imageUrl: PlaceHolderImages.find(p => p.id === 'item-7')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'item-7')?.imageHint || '',
    userId: 'user-2',
  },
  {
    id: '8',
    name: 'Ray-Ban Sunglasses',
    description: 'Lost my black Ray-Ban sunglasses, likely at the outdoor seating area of the coffee shop.',
    category: categories[3],
    status: 'lost',
    location: 'Coffee Shop',
    date: '2024-07-21',
    imageUrl: PlaceHolderImages.find(p => p.id === 'item-8')?.imageUrl || '',
    imageHint: PlaceHolderImages.find(p => p.id === 'item-8')?.imageHint || '',
    userId: 'user-1',
  },
];

export const claims: Claim[] = [
    { id: 'claim-1', itemId: '2', userId: 'user-1', date: '2024-07-20', status: 'pending', message: 'I think this is my textbook, I can describe the highlighting.' },
    { id: 'claim-2', itemId: '4', userId: 'user-2', date: '2024-07-22', status: 'approved', message: 'This is my water bottle, it has a sticker of a mountain and a cat.' },
    { id: 'claim-3', itemId: '5', userId: 'user-1', date: '2024-07-19', status: 'rejected', message: 'This is my wallet.' },
];
